### ISSUE TITLE
Remove leading and trailing spaces from secret values

### ISSUE THREAD

**Issue by JonathanViau** [emartech/gap-secret-editor#42]
We had an issue where copy/pasting a value in the editor introduced a space at the beginning of the secret value.
This situation caused an error in our app because of this invalid character. 
Could we at least trim the leading and trailing spaces and maybe detect other invalid characters (like bullets copied from an email or a Word document)?

**Comment by hawser86** [comment]
Hi, this is a very good idea. The philosophy of the Secret Editor is that it allows you to save whatever you want, and only displays warnings if a validation fails. E.g. if the secret value is a malformed JSON, you get a notification, but you can save it, if you really want it. Based on this, I would not trim the values automatically, but I can imagine a new warning notification if there is a whitespace at the beginning or at the end.

**Comment by hawser86** [comment]
Hi, I hope the new features in the [1.16.0](https://github.com/emartech/gap-secret-editor/releases/tag/v1.16.0) version will help your issue.
